
[DATA_NODE.prompt]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

[TASK.process_prompt]
inputs = [ "prompt:SECTION" ]
outputs = [ "response_data:SECTION" ]
function = "functions.check_prompts:function"
skippable = "False:bool"

[SCENARIO.llm_request_instruction]
additional_data_nodes = [ ]
tasks = [ "process_prompt:SECTION" ]

[DATA_NODE.response_data]
storage_type = "pickle"
scope = "SCENARIO:SCOPE"

