[CORE]
core_version = "3.0"







[DATA_NODE.result_data]
storage_type = "pickle"

scope = "SCENARIO:SCOPE"














[TASK.process_list]
inputs = [ "path_or_data:SECTION", "conversation_id:SECTION" ]
outputs = [ "result_data:SECTION" ]
function = "functions.llm_process_list_of_prompts:function"
skippable = "False:bool"



[SCENARIO.process_list_of_prompts]
additional_data_nodes = [ ]
tasks = [ "process_list:SECTION" ]









[DATA_NODE.path_or_data]
storage_type = "json"
default_data = "data/prompts/benchmarks/jokes.json"
scope = "SCENARIO:SCOPE"







[DATA_NODE.conversation_id]
storage_type = "pickle"
default_data = "modeltest"
scope = "SCENARIO:SCOPE"
